url: https://example.com
title: Test
author:
  name: A Tester
  # email: xxx@example.com
  uri: https://example.com/
description: "Your site description"
copyright: "Copyright © 2023 Your Name"

timezone: Europe/Berlin
date_format: "%b %-d, %Y"
date_format_long: "%B %-d, %Y"

## Github Pages Plugins
# https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
# https://pages.github.com/versions/ Jekyll 3.9.3 vs. 4.3.3
plugins:
  - jekyll-feed # 0.15.1 vs. 0.17
  - jekyll-remote-theme # 0.4.3
  - jekyll-sitemap # 1.4.0

## jekyll-feed
lang: en-US
feed:
  posts_limit: 1000000
  # excerpt_only: false

remote_theme: michaelnordmeyer/jekyll-theme-etch

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
