url: https://example.com
title: Test
author:
  name: A Tester
  # email: xxx@example.com
  uri: https://example.com/
description: "Your site description"
copyright: "Copyright © 2024 A Tester"

timezone: Europe/Berlin
date_format: "%b %-d, %Y"
date_format_long: "%B %-d, %Y"

## jekyll-feed
lang: en-US
feed:
  # posts_limit: 1000000
  # excerpt_only: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
