name = "Nix"
license = "MIT"
description = "A barebones theme for Zola"
homepage = "https://github.com/michaelnordmeyer.com/hugo-theme-nix"
demo = "https://hugo-theme-nix.michaelnordmeyer.com/"
min_version = "0.100"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
  name = "Michael Nordmeyer"
  homepage = "https://michaelnordmeyer.com/"
